[versions]
asm     = "9.4"      # https://asm.ow2.io/versions.html
lombok  = "1.18.26"

[libraries]
asm     = { module = "org.ow2.asm:asm",          version.ref = "asm" }
asmtree = { module = "org.ow2.asm:asm-tree",     version.ref = "asm" }
asmutil = { module = "org.ow2.asm:asm-util",     version.ref = "asm" }
lombok  = { module = "org.projectlombok:lombok", version.ref = "lombok"}
